// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqxnojfagpdrrdgdmdgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xeG5vamZhZ3BkcnJkZ2RtZGdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjMyMTMsImV4cCI6MjA2MTk5OTIxM30.cS1AyXAmzzFw9hUtZSmqD6BGgqbbh3ZF60QG-ihdR5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);